# coding: utf-8

"""
    Forem API V1

    Access Forem articles, users and other resources via API.         For a real-world example of Forem in action, check out [DEV](https://www.dev.to).         All endpoints can be accessed with the 'api-key' header and a accept header, but         some of them are accessible publicly without authentication.          Dates and date times, unless otherwise specified, must be in         the [RFC 3339](https://tools.ietf.org/html/rfc3339) format.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from dataclasses import dataclass
import typing_extensions
import urllib3
from pydantic import RootModel
from dev_python_sdk.request_before_hook import request_before_hook
import json
from urllib3._collections import HTTPHeaderDict

from dev_python_sdk.api_response import AsyncGeneratorResponse
from dev_python_sdk import api_client, exceptions
from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from dev_python_sdk import schemas  # noqa: F401

from dev_python_sdk.model.articles_list_published_articles_response import ArticlesListPublishedArticlesResponse as ArticlesListPublishedArticlesResponseSchema

from dev_python_sdk.type.articles_list_published_articles_response import ArticlesListPublishedArticlesResponse

from ...api_client import Dictionary
from dev_python_sdk.pydantic.articles_list_published_articles_response import ArticlesListPublishedArticlesResponse as ArticlesListPublishedArticlesResponsePydantic

from . import path

# Query params


class PageSchema(
    schemas.Int32Schema
):


    class MetaOapg:
        format = 'int32'
        inclusive_minimum = 1


class PerPageSchema(
    schemas.Int32Schema
):


    class MetaOapg:
        format = 'int32'
        inclusive_maximum = 1000
        inclusive_minimum = 1
TagSchema = schemas.StrSchema
TagsSchema = schemas.StrSchema
TagsExcludeSchema = schemas.StrSchema
UsernameSchema = schemas.StrSchema


class StateSchema(
    schemas.EnumBase,
    schemas.StrSchema
):


    class MetaOapg:
        enum_value_to_name = {
            "fresh": "FRESH",
            "rising": "RISING",
            "all": "ALL",
        }
    
    @schemas.classproperty
    def FRESH(cls):
        return cls("fresh")
    
    @schemas.classproperty
    def RISING(cls):
        return cls("rising")
    
    @schemas.classproperty
    def ALL(cls):
        return cls("all")


class TopSchema(
    schemas.Int32Schema
):


    class MetaOapg:
        format = 'int32'
        inclusive_minimum = 1
CollectionIdSchema = schemas.Int32Schema
RequestRequiredQueryParams = typing_extensions.TypedDict(
    'RequestRequiredQueryParams',
    {
    }
)
RequestOptionalQueryParams = typing_extensions.TypedDict(
    'RequestOptionalQueryParams',
    {
        'page': typing.Union[PageSchema, decimal.Decimal, int, ],
        'per_page': typing.Union[PerPageSchema, decimal.Decimal, int, ],
        'tag': typing.Union[TagSchema, str, ],
        'tags': typing.Union[TagsSchema, str, ],
        'tags_exclude': typing.Union[TagsExcludeSchema, str, ],
        'username': typing.Union[UsernameSchema, str, ],
        'state': typing.Union[StateSchema, str, ],
        'top': typing.Union[TopSchema, decimal.Decimal, int, ],
        'collection_id': typing.Union[CollectionIdSchema, decimal.Decimal, int, ],
    },
    total=False
)


class RequestQueryParams(RequestRequiredQueryParams, RequestOptionalQueryParams):
    pass


request_query_page = api_client.QueryParameter(
    name="page",
    style=api_client.ParameterStyle.FORM,
    schema=PageSchema,
    explode=True,
)
request_query_per_page = api_client.QueryParameter(
    name="per_page",
    style=api_client.ParameterStyle.FORM,
    schema=PerPageSchema,
    explode=True,
)
request_query_tag = api_client.QueryParameter(
    name="tag",
    style=api_client.ParameterStyle.FORM,
    schema=TagSchema,
    explode=True,
)
request_query_tags = api_client.QueryParameter(
    name="tags",
    style=api_client.ParameterStyle.FORM,
    schema=TagsSchema,
    explode=True,
)
request_query_tags_exclude = api_client.QueryParameter(
    name="tags_exclude",
    style=api_client.ParameterStyle.FORM,
    schema=TagsExcludeSchema,
    explode=True,
)
request_query_username = api_client.QueryParameter(
    name="username",
    style=api_client.ParameterStyle.FORM,
    schema=UsernameSchema,
    explode=True,
)
request_query_state = api_client.QueryParameter(
    name="state",
    style=api_client.ParameterStyle.FORM,
    schema=StateSchema,
    explode=True,
)
request_query_top = api_client.QueryParameter(
    name="top",
    style=api_client.ParameterStyle.FORM,
    schema=TopSchema,
    explode=True,
)
request_query_collection_id = api_client.QueryParameter(
    name="collection_id",
    style=api_client.ParameterStyle.FORM,
    schema=CollectionIdSchema,
    explode=True,
)
SchemaFor200ResponseBodyApplicationJson = ArticlesListPublishedArticlesResponseSchema


@dataclass
class ApiResponseFor200(api_client.ApiResponse):
    body: ArticlesListPublishedArticlesResponse


@dataclass
class ApiResponseFor200Async(api_client.AsyncApiResponse):
    body: ArticlesListPublishedArticlesResponse


_response_for_200 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor200,
    response_cls_async=ApiResponseFor200Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationJson),
    },
)
_status_code_to_response = {
    '200': _response_for_200,
}
_all_accept_content_types = (
    'application/json',
)


class BaseApi(api_client.Api):

    def _list_published_articles_mapped_args(
        self,
        page: typing.Optional[int] = None,
        per_page: typing.Optional[int] = None,
        tag: typing.Optional[str] = None,
        tags: typing.Optional[str] = None,
        tags_exclude: typing.Optional[str] = None,
        username: typing.Optional[str] = None,
        state: typing.Optional[str] = None,
        top: typing.Optional[int] = None,
        collection_id: typing.Optional[int] = None,
    ) -> api_client.MappedArgs:
        args: api_client.MappedArgs = api_client.MappedArgs()
        _query_params = {}
        if page is not None:
            _query_params["page"] = page
        if per_page is not None:
            _query_params["per_page"] = per_page
        if tag is not None:
            _query_params["tag"] = tag
        if tags is not None:
            _query_params["tags"] = tags
        if tags_exclude is not None:
            _query_params["tags_exclude"] = tags_exclude
        if username is not None:
            _query_params["username"] = username
        if state is not None:
            _query_params["state"] = state
        if top is not None:
            _query_params["top"] = top
        if collection_id is not None:
            _query_params["collection_id"] = collection_id
        args.query = _query_params
        return args

    async def _alist_published_articles_oapg(
        self,
            query_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        """
        Published articles
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestQueryParams, query_params)
        used_path = path.value
    
        prefix_separator_iterator = None
        for parameter in (
            request_query_page,
            request_query_per_page,
            request_query_tag,
            request_query_tags,
            request_query_tags_exclude,
            request_query_username,
            request_query_state,
            request_query_top,
            request_query_collection_id,
        ):
            parameter_data = query_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            if prefix_separator_iterator is None:
                prefix_separator_iterator = parameter.get_prefix_separator_iterator()
            serialized_data = parameter.serialize(parameter_data, prefix_separator_iterator)
            for serialized_value in serialized_data.values():
                used_path += serialized_value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'get'.upper()
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/api/articles',
            headers=_headers,
        )
    
        response = await self.api_client.async_call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            prefix_separator_iterator=prefix_separator_iterator,
            timeout=timeout,
            **kwargs
        )
    
        if stream:
            if not 200 <= response.http_response.status <= 299:
                body = (await response.http_response.content.read()).decode("utf-8")
                raise exceptions.ApiStreamingException(
                    status=response.http_response.status,
                    reason=response.http_response.reason,
                    body=body,
                )
    
            async def stream_iterator():
                """
                iterates over response.http_response.content and closes connection once iteration has finished
                """
                async for line in response.http_response.content:
                    if line == b'\r\n':
                        continue
                    yield line
                response.http_response.close()
                await response.session.close()
            return AsyncGeneratorResponse(
                content=stream_iterator(),
                headers=response.http_response.headers,
                status=response.http_response.status,
                response=response.http_response
            )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = await response_for_status.deserialize_async(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserializationAsync(
                body=await response.http_response.json() if is_json else await response.http_response.text(),
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        # cleanup session / response
        response.http_response.close()
        await response.session.close()
    
        return api_response


    def _list_published_articles_oapg(
        self,
            query_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        """
        Published articles
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestQueryParams, query_params)
        used_path = path.value
    
        prefix_separator_iterator = None
        for parameter in (
            request_query_page,
            request_query_per_page,
            request_query_tag,
            request_query_tags,
            request_query_tags_exclude,
            request_query_username,
            request_query_state,
            request_query_top,
            request_query_collection_id,
        ):
            parameter_data = query_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            if prefix_separator_iterator is None:
                prefix_separator_iterator = parameter.get_prefix_separator_iterator()
            serialized_data = parameter.serialize(parameter_data, prefix_separator_iterator)
            for serialized_value in serialized_data.values():
                used_path += serialized_value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'get'.upper()
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/api/articles',
            headers=_headers,
        )
    
        response = self.api_client.call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            prefix_separator_iterator=prefix_separator_iterator,
            timeout=timeout,
        )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = response_for_status.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserialization(
                body=json.loads(response.http_response.data) if is_json else response.http_response.data,
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        return api_response


class ListPublishedArticlesRaw(BaseApi):
    # this class is used by api classes that refer to endpoints with operationId fn names

    async def alist_published_articles(
        self,
        page: typing.Optional[int] = None,
        per_page: typing.Optional[int] = None,
        tag: typing.Optional[str] = None,
        tags: typing.Optional[str] = None,
        tags_exclude: typing.Optional[str] = None,
        username: typing.Optional[str] = None,
        state: typing.Optional[str] = None,
        top: typing.Optional[int] = None,
        collection_id: typing.Optional[int] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._list_published_articles_mapped_args(
            page=page,
            per_page=per_page,
            tag=tag,
            tags=tags,
            tags_exclude=tags_exclude,
            username=username,
            state=state,
            top=top,
            collection_id=collection_id,
        )
        return await self._alist_published_articles_oapg(
            query_params=args.query,
            **kwargs,
        )
    
    def list_published_articles(
        self,
        page: typing.Optional[int] = None,
        per_page: typing.Optional[int] = None,
        tag: typing.Optional[str] = None,
        tags: typing.Optional[str] = None,
        tags_exclude: typing.Optional[str] = None,
        username: typing.Optional[str] = None,
        state: typing.Optional[str] = None,
        top: typing.Optional[int] = None,
        collection_id: typing.Optional[int] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._list_published_articles_mapped_args(
            page=page,
            per_page=per_page,
            tag=tag,
            tags=tags,
            tags_exclude=tags_exclude,
            username=username,
            state=state,
            top=top,
            collection_id=collection_id,
        )
        return self._list_published_articles_oapg(
            query_params=args.query,
        )

class ListPublishedArticles(BaseApi):

    async def alist_published_articles(
        self,
        page: typing.Optional[int] = None,
        per_page: typing.Optional[int] = None,
        tag: typing.Optional[str] = None,
        tags: typing.Optional[str] = None,
        tags_exclude: typing.Optional[str] = None,
        username: typing.Optional[str] = None,
        state: typing.Optional[str] = None,
        top: typing.Optional[int] = None,
        collection_id: typing.Optional[int] = None,
        validate: bool = False,
        **kwargs,
    ) -> ArticlesListPublishedArticlesResponsePydantic:
        raw_response = await self.raw.alist_published_articles(
            page=page,
            per_page=per_page,
            tag=tag,
            tags=tags,
            tags_exclude=tags_exclude,
            username=username,
            state=state,
            top=top,
            collection_id=collection_id,
            **kwargs,
        )
        if validate:
            return RootModel[ArticlesListPublishedArticlesResponsePydantic](raw_response.body).root
        return api_client.construct_model_instance(ArticlesListPublishedArticlesResponsePydantic, raw_response.body)
    
    
    def list_published_articles(
        self,
        page: typing.Optional[int] = None,
        per_page: typing.Optional[int] = None,
        tag: typing.Optional[str] = None,
        tags: typing.Optional[str] = None,
        tags_exclude: typing.Optional[str] = None,
        username: typing.Optional[str] = None,
        state: typing.Optional[str] = None,
        top: typing.Optional[int] = None,
        collection_id: typing.Optional[int] = None,
        validate: bool = False,
    ) -> ArticlesListPublishedArticlesResponsePydantic:
        raw_response = self.raw.list_published_articles(
            page=page,
            per_page=per_page,
            tag=tag,
            tags=tags,
            tags_exclude=tags_exclude,
            username=username,
            state=state,
            top=top,
            collection_id=collection_id,
        )
        if validate:
            return RootModel[ArticlesListPublishedArticlesResponsePydantic](raw_response.body).root
        return api_client.construct_model_instance(ArticlesListPublishedArticlesResponsePydantic, raw_response.body)


class ApiForget(BaseApi):
    # this class is used by api classes that refer to endpoints by path and http method names

    async def aget(
        self,
        page: typing.Optional[int] = None,
        per_page: typing.Optional[int] = None,
        tag: typing.Optional[str] = None,
        tags: typing.Optional[str] = None,
        tags_exclude: typing.Optional[str] = None,
        username: typing.Optional[str] = None,
        state: typing.Optional[str] = None,
        top: typing.Optional[int] = None,
        collection_id: typing.Optional[int] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._list_published_articles_mapped_args(
            page=page,
            per_page=per_page,
            tag=tag,
            tags=tags,
            tags_exclude=tags_exclude,
            username=username,
            state=state,
            top=top,
            collection_id=collection_id,
        )
        return await self._alist_published_articles_oapg(
            query_params=args.query,
            **kwargs,
        )
    
    def get(
        self,
        page: typing.Optional[int] = None,
        per_page: typing.Optional[int] = None,
        tag: typing.Optional[str] = None,
        tags: typing.Optional[str] = None,
        tags_exclude: typing.Optional[str] = None,
        username: typing.Optional[str] = None,
        state: typing.Optional[str] = None,
        top: typing.Optional[int] = None,
        collection_id: typing.Optional[int] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._list_published_articles_mapped_args(
            page=page,
            per_page=per_page,
            tag=tag,
            tags=tags,
            tags_exclude=tags_exclude,
            username=username,
            state=state,
            top=top,
            collection_id=collection_id,
        )
        return self._list_published_articles_oapg(
            query_params=args.query,
        )

