# coding: utf-8

"""
    Forem API V1

    Access Forem articles, users and other resources via API.         For a real-world example of Forem in action, check out [DEV](https://www.dev.to).         All endpoints can be accessed with the 'api-key' header and a accept header, but         some of them are accessible publicly without authentication.          Dates and date times, unless otherwise specified, must be in         the [RFC 3339](https://tools.ietf.org/html/rfc3339) format.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from dev_python_sdk.paths.api_articles.post import CreateNewArticleRaw
from dev_python_sdk.paths.api_articles_me_all.get import GetAllUserArticlesRaw
from dev_python_sdk.paths.api_articles_id.get import GetByIdRaw
from dev_python_sdk.paths.api_articles_username_slug.get import GetByPathRaw
from dev_python_sdk.paths.api_articles_me.get import GetPublishedListRaw
from dev_python_sdk.paths.api_articles_me_published.get import GetPublishedList0Raw
from dev_python_sdk.paths.api_articles_me_unpublished.get import GetUnpublishedListRaw
from dev_python_sdk.paths.api_organizations_organization_id_or_username_articles.get import ListArticlesRaw
from dev_python_sdk.paths.api_videos.get import ListByPopularityRaw
from dev_python_sdk.paths.api_articles_latest.get import ListLatestPublishedRaw
from dev_python_sdk.paths.api_articles.get import ListPublishedArticlesRaw
from dev_python_sdk.paths.api_articles_id_unpublish.put import UnpublishByIdRaw
from dev_python_sdk.paths.api_articles_id.put import UpdateByIdRaw


class ArticlesApiRaw(
    CreateNewArticleRaw,
    GetAllUserArticlesRaw,
    GetByIdRaw,
    GetByPathRaw,
    GetPublishedListRaw,
    GetPublishedList0Raw,
    GetUnpublishedListRaw,
    ListArticlesRaw,
    ListByPopularityRaw,
    ListLatestPublishedRaw,
    ListPublishedArticlesRaw,
    UnpublishByIdRaw,
    UpdateByIdRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
