# coding: utf-8

"""
    Forem API V1

    Access Forem articles, users and other resources via API.         For a real-world example of Forem in action, check out [DEV](https://www.dev.to).         All endpoints can be accessed with the 'api-key' header and a accept header, but         some of them are accessible publicly without authentication.          Dates and date times, unless otherwise specified, must be in         the [RFC 3339](https://tools.ietf.org/html/rfc3339) format.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from dev_python_sdk.paths.api_organizations.post import CreateNewOrganizationRaw
from dev_python_sdk.paths.api_organizations_id.delete import DeleteByIdRaw
from dev_python_sdk.paths.api_organizations_id.get import GetByIdRaw
from dev_python_sdk.paths.api_organizations_username.get import GetByUsernameRaw
from dev_python_sdk.paths.api_organizations_organization_id_or_username_articles.get import ListArticlesRaw
from dev_python_sdk.paths.api_organizations.get import ListOfDevRaw
from dev_python_sdk.paths.api_organizations_organization_id_or_username_users.get import ListUsersRaw
from dev_python_sdk.paths.api_organizations_id.put import UpdateByIdRaw


class OrganizationsApiRaw(
    CreateNewOrganizationRaw,
    DeleteByIdRaw,
    GetByIdRaw,
    GetByUsernameRaw,
    ListArticlesRaw,
    ListOfDevRaw,
    ListUsersRaw,
    UpdateByIdRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
