# coding: utf-8

"""
    Forem API V1

    Access Forem articles, users and other resources via API.         For a real-world example of Forem in action, check out [DEV](https://www.dev.to).         All endpoints can be accessed with the 'api-key' header and a accept header, but         some of them are accessible publicly without authentication.          Dates and date times, unless otherwise specified, must be in         the [RFC 3339](https://tools.ietf.org/html/rfc3339) format.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from dev_python_sdk.paths.api_segments_id_add_users.put import AddUsersToSegment
from dev_python_sdk.paths.api_segments.post import CreateManuallyManagedSegment
from dev_python_sdk.paths.api_segments_id.delete import DeleteManuallyManagedSegment
from dev_python_sdk.paths.api_segments_id.get import GetById
from dev_python_sdk.paths.api_segments_id_users.get import GetUserListInSegment
from dev_python_sdk.paths.api_segments.get import ListAudienceSegments
from dev_python_sdk.paths.api_segments_id_remove_users.put import RemoveUsersFromSegment
from dev_python_sdk.apis.tags.segments_api_raw import SegmentsApiRaw


class SegmentsApi(
    AddUsersToSegment,
    CreateManuallyManagedSegment,
    DeleteManuallyManagedSegment,
    GetById,
    GetUserListInSegment,
    ListAudienceSegments,
    RemoveUsersFromSegment,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: SegmentsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = SegmentsApiRaw(api_client)
