# coding: utf-8

"""
    Forem API V1

    Access Forem articles, users and other resources via API.         For a real-world example of Forem in action, check out [DEV](https://www.dev.to).         All endpoints can be accessed with the 'api-key' header and a accept header, but         some of them are accessible publicly without authentication.          Dates and date times, unless otherwise specified, must be in         the [RFC 3339](https://tools.ietf.org/html/rfc3339) format.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from dev_python_sdk.paths.api_users_id_limited.put import AddLimitedRoleRaw
from dev_python_sdk.paths.api_users_id_trusted.put import AddTrustedRoleRaw
from dev_python_sdk.paths.api_users_id_spam.put import AssignSpamRoleRaw
from dev_python_sdk.paths.api_articles_me_all.get import GetAllUserArticlesRaw
from dev_python_sdk.paths.api_users_id.get import GetByIdOrUsernameRaw
from dev_python_sdk.paths.api_users_me.get import GetInformationRaw
from dev_python_sdk.paths.api_articles_me.get import GetPublishedListRaw
from dev_python_sdk.paths.api_articles_me_published.get import GetPublishedList0Raw
from dev_python_sdk.paths.api_articles_me_unpublished.get import GetUnpublishedListRaw
from dev_python_sdk.paths.api_admin_users.post import InviteUserRaw
from dev_python_sdk.paths.api_organizations_organization_id_or_username_users.get import ListUsersRaw
from dev_python_sdk.paths.api_users_id_limited.delete import RemoveLimitsRaw
from dev_python_sdk.paths.api_users_id_spam.delete import RemoveSpamRoleRaw
from dev_python_sdk.paths.api_users_id_trusted.delete import RemoveTrustedRoleRaw
from dev_python_sdk.paths.api_users_id_suspend.put import SuspendUserRaw
from dev_python_sdk.paths.api_users_id_unpublish.put import UnpublishUserArticlesAndCommentsRaw


class UsersApiRaw(
    AddLimitedRoleRaw,
    AddTrustedRoleRaw,
    AssignSpamRoleRaw,
    GetAllUserArticlesRaw,
    GetByIdOrUsernameRaw,
    GetInformationRaw,
    GetPublishedListRaw,
    GetPublishedList0Raw,
    GetUnpublishedListRaw,
    InviteUserRaw,
    ListUsersRaw,
    RemoveLimitsRaw,
    RemoveSpamRoleRaw,
    RemoveTrustedRoleRaw,
    SuspendUserRaw,
    UnpublishUserArticlesAndCommentsRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
