# coding: utf-8

"""
    Forem API V1

    Access Forem articles, users and other resources via API.         For a real-world example of Forem in action, check out [DEV](https://www.dev.to).         All endpoints can be accessed with the 'api-key' header and a accept header, but         some of them are accessible publicly without authentication.          Dates and date times, unless otherwise specified, must be in         the [RFC 3339](https://tools.ietf.org/html/rfc3339) format.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class ArticleArticle(BaseModel):
    tags: typing.Optional[str] = Field(None, alias='tags')

    title: typing.Optional[str] = Field(None, alias='title')

    description: typing.Optional[str] = Field(None, alias='description')

    body_markdown: typing.Optional[str] = Field(None, alias='body_markdown')

    published: typing.Optional[bool] = Field(None, alias='published')

    series: typing.Optional[typing.Optional[str]] = Field(None, alias='series')

    main_image: typing.Optional[typing.Optional[str]] = Field(None, alias='main_image')

    canonical_url: typing.Optional[typing.Optional[str]] = Field(None, alias='canonical_url')

    organization_id: typing.Optional[typing.Optional[int]] = Field(None, alias='organization_id')
    class Config:
        arbitrary_types_allowed = True
