# coding: utf-8

"""
    Forem API V1

    Access Forem articles, users and other resources via API.         For a real-world example of Forem in action, check out [DEV](https://www.dev.to).         All endpoints can be accessed with the 'api-key' header and a accept header, but         some of them are accessible publicly without authentication.          Dates and date times, unless otherwise specified, must be in         the [RFC 3339](https://tools.ietf.org/html/rfc3339) format.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from dev_python_sdk.pydantic.comments_get_threaded_comment_response_children import CommentsGetThreadedCommentResponseChildren
from dev_python_sdk.pydantic.comments_get_threaded_comment_response_user import CommentsGetThreadedCommentResponseUser

class CommentsGetThreadedCommentResponse(BaseModel):
    type_of: typing.Optional[str] = Field(None, alias='type_of')

    id_code: typing.Optional[str] = Field(None, alias='id_code')

    created_at: typing.Optional[str] = Field(None, alias='created_at')

    body_html: typing.Optional[str] = Field(None, alias='body_html')

    user: typing.Optional[CommentsGetThreadedCommentResponseUser] = Field(None, alias='user')

    children: typing.Optional[CommentsGetThreadedCommentResponseChildren] = Field(None, alias='children')
    class Config:
        arbitrary_types_allowed = True
