# coding: utf-8

"""
    Forem API V1

    Access Forem articles, users and other resources via API.         For a real-world example of Forem in action, check out [DEV](https://www.dev.to).         All endpoints can be accessed with the 'api-key' header and a accept header, but         some of them are accessible publicly without authentication.          Dates and date times, unless otherwise specified, must be in         the [RFC 3339](https://tools.ietf.org/html/rfc3339) format.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from dev_python_sdk.pydantic.pages_update_page_details422_response_social_image import PagesUpdatePageDetails422ResponseSocialImage

class PagesUpdatePageDetails422Response(BaseModel):
    title: typing.Optional[str] = Field(None, alias='title')

    description: typing.Optional[str] = Field(None, alias='description')

    id: typing.Optional[typing.Union[int, float]] = Field(None, alias='id')

    slug: typing.Optional[str] = Field(None, alias='slug')

    is_top_level_path: typing.Optional[bool] = Field(None, alias='is_top_level_path')

    landing_page: typing.Optional[bool] = Field(None, alias='landing_page')

    body_html: typing.Optional[typing.Optional[str]] = Field(None, alias='body_html')

    body_json: typing.Optional[typing.Optional[str]] = Field(None, alias='body_json')

    body_markdown: typing.Optional[str] = Field(None, alias='body_markdown')

    processed_html: typing.Optional[str] = Field(None, alias='processed_html')

    social_image: typing.Optional[PagesUpdatePageDetails422ResponseSocialImage] = Field(None, alias='social_image')

    template: typing.Optional[str] = Field(None, alias='template')
    class Config:
        arbitrary_types_allowed = True
