# coding: utf-8

"""
    Forem API V1

    Access Forem articles, users and other resources via API.         For a real-world example of Forem in action, check out [DEV](https://www.dev.to).         All endpoints can be accessed with the 'api-key' header and a accept header, but         some of them are accessible publicly without authentication.          Dates and date times, unless otherwise specified, must be in         the [RFC 3339](https://tools.ietf.org/html/rfc3339) format.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from dev_python_sdk.pydantic.pages_remove_page_by_id422_response_doubled_module import PagesRemovePageById422ResponseDoubledModule

class PagesRemovePageById422Response(BaseModel):
    doubled_module: typing.Optional[PagesRemovePageById422ResponseDoubledModule] = Field(None, alias='doubled_module')

    __expired: typing.Optional[bool] = Field(None, alias='__expired')

    name: typing.Optional[typing.Optional[str]] = Field(None, alias='name')

    __sending_message: typing.Optional[typing.Optional[str]] = Field(None, alias='__sending_message')
    class Config:
        arbitrary_types_allowed = True
