# coding: utf-8

"""
    Forem API V1

    Access Forem articles, users and other resources via API.         For a real-world example of Forem in action, check out [DEV](https://www.dev.to).         All endpoints can be accessed with the 'api-key' header and a accept header, but         some of them are accessible publicly without authentication.          Dates and date times, unless otherwise specified, must be in         the [RFC 3339](https://tools.ietf.org/html/rfc3339) format.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class Page(BaseModel):
    # Title of the page
    title: str = Field(alias='title')

    # For internal use, helps similar pages from one another
    description: str = Field(alias='description')

    # Used to link to this page in URLs, must be unique and URL-safe
    slug: str = Field(alias='slug')

    # Controls what kind of layout the page is rendered in
    template: Literal["contained", "full_within_layout", "nav_bar_included", "json"] = Field(alias='template')

    # The text (in markdown) of the ad (required)
    body_markdown: typing.Optional[typing.Optional[str]] = Field(None, alias='body_markdown')

    # For JSON pages, the JSON body
    body_json: typing.Optional[typing.Optional[str]] = Field(None, alias='body_json')

    # If true, the page is available at '/{slug}' instead of '/page/{slug}', use with caution
    is_top_level_path: typing.Optional[bool] = Field(None, alias='is_top_level_path')

    social_image: typing.Optional[typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]]] = Field(None, alias='social_image')
    class Config:
        arbitrary_types_allowed = True
