# coding: utf-8

"""
    Forem API V1

    Access Forem articles, users and other resources via API.         For a real-world example of Forem in action, check out [DEV](https://www.dev.to).         All endpoints can be accessed with the 'api-key' header and a accept header, but         some of them are accessible publicly without authentication.          Dates and date times, unless otherwise specified, must be in         the [RFC 3339](https://tools.ietf.org/html/rfc3339) format.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from dev_python_sdk.pydantic.video_article_user import VideoArticleUser

class VideoArticle(BaseModel):
    title: typing.Optional[str] = Field(None, alias='title')

    type_of: typing.Optional[str] = Field(None, alias='type_of')

    id: typing.Optional[int] = Field(None, alias='id')

    path: typing.Optional[str] = Field(None, alias='path')

    cloudinary_video_url: typing.Optional[str] = Field(None, alias='cloudinary_video_url')

    user_id: typing.Optional[int] = Field(None, alias='user_id')

    video_duration_in_minutes: typing.Optional[str] = Field(None, alias='video_duration_in_minutes')

    video_source_url: typing.Optional[str] = Field(None, alias='video_source_url')

    user: typing.Optional[VideoArticleUser] = Field(None, alias='user')
    class Config:
        arbitrary_types_allowed = True
