# coding: utf-8

"""
    Forem API V1

    Access Forem articles, users and other resources via API.         For a real-world example of Forem in action, check out [DEV](https://www.dev.to).         All endpoints can be accessed with the 'api-key' header and a accept header, but         some of them are accessible publicly without authentication.          Dates and date times, unless otherwise specified, must be in         the [RFC 3339](https://tools.ietf.org/html/rfc3339) format.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from dev_python_sdk.type.article_flare_tag import ArticleFlareTag
from dev_python_sdk.type.article_index_tag_list import ArticleIndexTagList
from dev_python_sdk.type.shared_organization import SharedOrganization
from dev_python_sdk.type.shared_user import SharedUser

class RequiredArticleIndex(TypedDict):
    tags: str

    title: str

    description: str

    type_of: str

    id: int

    cover_image: typing.Optional[str]

    readable_publish_date: str

    social_image: str

    tag_list: ArticleIndexTagList

    slug: str

    path: str

    url: str

    canonical_url: str

    positive_reactions_count: int

    public_reactions_count: int

    created_at: datetime

    edited_at: typing.Optional[datetime]

    crossposted_at: typing.Optional[datetime]

    published_at: datetime

    last_comment_at: datetime

    # Crossposting or published date time
    published_timestamp: datetime

    # Reading time, in minutes
    reading_time_minutes: int

    user: SharedUser

class OptionalArticleIndex(TypedDict, total=False):
    flare_tag: ArticleFlareTag

    organization: SharedOrganization

class ArticleIndex(RequiredArticleIndex, OptionalArticleIndex):
    pass
