# coding: utf-8

"""
    Forem API V1

    Access Forem articles, users and other resources via API.         For a real-world example of Forem in action, check out [DEV](https://www.dev.to).         All endpoints can be accessed with the 'api-key' header and a accept header, but         some of them are accessible publicly without authentication.          Dates and date times, unless otherwise specified, must be in         the [RFC 3339](https://tools.ietf.org/html/rfc3339) format.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from dev_python_sdk.type.billboard_target_geolocations import BillboardTargetGeolocations

class RequiredBillboard(TypedDict):
    # For internal use, helps distinguish ads from one another
    name: str

    # The text (in markdown) of the ad (required)
    body_markdown: str

    # Identifies which area of site layout the ad can appear in
    placement_area: str

class OptionalBillboard(TypedDict, total=False):
    # The ID of the Billboard
    id: int

    # Ad must be both published and approved to be in rotation
    approved: bool

    # Ad must be both published and approved to be in rotation
    published: bool

    # Identifies the organization to which the ad belongs
    organization_id: typing.Optional[int]

    # Identifies the user who created the ad.
    creator_id: typing.Optional[int]

    # Tags on which this ad can be displayed (blank is all/any tags)
    tag_list: str

    # Articles this ad should *not* appear on (blank means no articles are disallowed, and this ad can appear next to any/all articles). Comma-separated list of integer Article IDs
    exclude_article_ids: typing.Optional[str]

    # Specifies a specific audience segment who will see this billboard
    audience_segment_id: int

    # Specifies a group of users who will see this billboard (must match audience_segment_id if both provided)
    audience_segment_type: str

    target_geolocations: BillboardTargetGeolocations

    # Potentially limits visitors to whom the ad is visible
    display_to: str

    # Types of the billboards: in_house (created by admins), community (created by an entity, appears on entity's content), external ( created by an entity, or a non-entity, can appear everywhere) 
    type_of: str

class Billboard(RequiredBillboard, OptionalBillboard):
    pass
