# coding: utf-8

"""
    Forem API V1

    Access Forem articles, users and other resources via API.         For a real-world example of Forem in action, check out [DEV](https://www.dev.to).         All endpoints can be accessed with the 'api-key' header and a accept header, but         some of them are accessible publicly without authentication.          Dates and date times, unless otherwise specified, must be in         the [RFC 3339](https://tools.ietf.org/html/rfc3339) format.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from dev_python_sdk.type.billboards_get_by_id_response_target_geolocations import BillboardsGetByIdResponseTargetGeolocations

class RequiredBillboardsGetByIdResponse(TypedDict):
    pass

class OptionalBillboardsGetByIdResponse(TypedDict, total=False):
    id: typing.Union[int, float]

    approved: bool

    audience_segment_id: typing.Optional[str]

    body_markdown: str

    cached_tag_list: str

    clicks_count: typing.Union[int, float]

    created_at: str

    creator_id: typing.Optional[str]

    custom_display_label: typing.Optional[str]

    display_to: str

    exclude_article_ids: str

    impressions_count: typing.Union[int, float]

    name: str

    organization_id: typing.Union[int, float]

    placement_area: str

    priority: bool

    processed_html: str

    published: bool

    render_mode: str

    success_rate: typing.Union[int, float]

    template: str

    type_of: str

    updated_at: str

    weight: typing.Union[int, float]

    audience_segment_type: typing.Optional[str]

    tag_list: str

    target_geolocations: BillboardsGetByIdResponseTargetGeolocations

class BillboardsGetByIdResponse(RequiredBillboardsGetByIdResponse, OptionalBillboardsGetByIdResponse):
    pass
