# coding: utf-8

"""
    Forem API V1

    Access Forem articles, users and other resources via API.         For a real-world example of Forem in action, check out [DEV](https://www.dev.to).         All endpoints can be accessed with the 'api-key' header and a accept header, but         some of them are accessible publicly without authentication.          Dates and date times, unless otherwise specified, must be in         the [RFC 3339](https://tools.ietf.org/html/rfc3339) format.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredOrganizationsCreateNewOrganizationResponse(TypedDict):
    pass

class OptionalOrganizationsCreateNewOrganizationResponse(TypedDict, total=False):
    summary: str

    id: typing.Union[int, float]

    name: str

    profile_image: str

    slug: str

    tag_line: str

    url: str

class OrganizationsCreateNewOrganizationResponse(RequiredOrganizationsCreateNewOrganizationResponse, OptionalOrganizationsCreateNewOrganizationResponse):
    pass
