# coding: utf-8

"""
    Forem API V1

    Access Forem articles, users and other resources via API.         For a real-world example of Forem in action, check out [DEV](https://www.dev.to).         All endpoints can be accessed with the 'api-key' header and a accept header, but         some of them are accessible publicly without authentication.          Dates and date times, unless otherwise specified, must be in         the [RFC 3339](https://tools.ietf.org/html/rfc3339) format.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredPagesCreateNewPageRequest(TypedDict):
    pass

class OptionalPagesCreateNewPageRequest(TypedDict, total=False):
    # Title of the page
    title: str

    # For internal use, helps similar pages from one another
    description: str

    # Used to link to this page in URLs, must be unique and URL-safe
    slug: str

    # The text (in markdown) of the ad (required)
    body_markdown: str

    # For JSON pages, the JSON body
    body_json: str

    # If true, the page is available at '/{slug}' instead of '/page/{slug}', use with caution
    is_top_level_path: bool

    # Controls what kind of layout the page is rendered in
    template: str

class PagesCreateNewPageRequest(RequiredPagesCreateNewPageRequest, OptionalPagesCreateNewPageRequest):
    pass
