# coding: utf-8

"""
    Forem API V1

    Access Forem articles, users and other resources via API.         For a real-world example of Forem in action, check out [DEV](https://www.dev.to).         All endpoints can be accessed with the 'api-key' header and a accept header, but         some of them are accessible publicly without authentication.          Dates and date times, unless otherwise specified, must be in         the [RFC 3339](https://tools.ietf.org/html/rfc3339) format.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from dev_python_sdk.type.segments_add_users_to_segment_response_failed import SegmentsAddUsersToSegmentResponseFailed
from dev_python_sdk.type.segments_add_users_to_segment_response_succeeded import SegmentsAddUsersToSegmentResponseSucceeded

class RequiredSegmentsAddUsersToSegmentResponse(TypedDict):
    pass

class OptionalSegmentsAddUsersToSegmentResponse(TypedDict, total=False):
    succeeded: SegmentsAddUsersToSegmentResponseSucceeded

    failed: SegmentsAddUsersToSegmentResponseFailed

class SegmentsAddUsersToSegmentResponse(RequiredSegmentsAddUsersToSegmentResponse, OptionalSegmentsAddUsersToSegmentResponse):
    pass
