# coding: utf-8

"""
    Forem API V1

    Access Forem articles, users and other resources via API.         For a real-world example of Forem in action, check out [DEV](https://www.dev.to).         All endpoints can be accessed with the 'api-key' header and a accept header, but         some of them are accessible publicly without authentication.          Dates and date times, unless otherwise specified, must be in         the [RFC 3339](https://tools.ietf.org/html/rfc3339) format.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import dev_python_sdk
from dev_python_sdk.model.segments_remove_users_from_segment401_response import SegmentsRemoveUsersFromSegment401Response
from dev_python_sdk import configuration


class TestSegmentsRemoveUsersFromSegment401Response(unittest.TestCase):
    """SegmentsRemoveUsersFromSegment401Response unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
