# coding: utf-8

"""
    Forem API V1

    Access Forem articles, users and other resources via API.         For a real-world example of Forem in action, check out [DEV](https://www.dev.to).         All endpoints can be accessed with the 'api-key' header and a accept header, but         some of them are accessible publicly without authentication.          Dates and date times, unless otherwise specified, must be in         the [RFC 3339](https://tools.ietf.org/html/rfc3339) format.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from dataclasses import dataclass
import typing_extensions
import urllib3
from pydantic import RootModel
from dev_python_sdk.request_before_hook import request_before_hook
import json
from urllib3._collections import HTTPHeaderDict

from dev_python_sdk.api_response import AsyncGeneratorResponse
from dev_python_sdk import api_client, exceptions
from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from dev_python_sdk import schemas  # noqa: F401

from dev_python_sdk.model.comments_get_all_threaded404_response import CommentsGetAllThreaded404Response as CommentsGetAllThreaded404ResponseSchema
from dev_python_sdk.model.comments_get_all_threaded_response import CommentsGetAllThreadedResponse as CommentsGetAllThreadedResponseSchema

from dev_python_sdk.type.comments_get_all_threaded_response import CommentsGetAllThreadedResponse
from dev_python_sdk.type.comments_get_all_threaded404_response import CommentsGetAllThreaded404Response

from ...api_client import Dictionary
from dev_python_sdk.pydantic.comments_get_all_threaded404_response import CommentsGetAllThreaded404Response as CommentsGetAllThreaded404ResponsePydantic
from dev_python_sdk.pydantic.comments_get_all_threaded_response import CommentsGetAllThreadedResponse as CommentsGetAllThreadedResponsePydantic

from . import path

# Query params


class PerPageSchema(
    schemas.Int32Schema
):


    class MetaOapg:
        format = 'int32'
        inclusive_maximum = 1000
        inclusive_minimum = 1
AIdSchema = schemas.StrSchema
PIdSchema = schemas.StrSchema


class PageSchema(
    schemas.Int32Schema
):


    class MetaOapg:
        format = 'int32'
        inclusive_minimum = 1
RequestRequiredQueryParams = typing_extensions.TypedDict(
    'RequestRequiredQueryParams',
    {
    }
)
RequestOptionalQueryParams = typing_extensions.TypedDict(
    'RequestOptionalQueryParams',
    {
        'per_page': typing.Union[PerPageSchema, decimal.Decimal, int, ],
        'a_id': typing.Union[AIdSchema, str, ],
        'p_id': typing.Union[PIdSchema, str, ],
        'page': typing.Union[PageSchema, decimal.Decimal, int, ],
    },
    total=False
)


class RequestQueryParams(RequestRequiredQueryParams, RequestOptionalQueryParams):
    pass


request_query_per_page = api_client.QueryParameter(
    name="per_page",
    style=api_client.ParameterStyle.FORM,
    schema=PerPageSchema,
    explode=True,
)
request_query_a_id = api_client.QueryParameter(
    name="a_id",
    style=api_client.ParameterStyle.FORM,
    schema=AIdSchema,
    explode=True,
)
request_query_p_id = api_client.QueryParameter(
    name="p_id",
    style=api_client.ParameterStyle.FORM,
    schema=PIdSchema,
    explode=True,
)
request_query_page = api_client.QueryParameter(
    name="page",
    style=api_client.ParameterStyle.FORM,
    schema=PageSchema,
    explode=True,
)
SchemaFor200ResponseBodyApplicationJson = CommentsGetAllThreadedResponseSchema


@dataclass
class ApiResponseFor200(api_client.ApiResponse):
    body: CommentsGetAllThreadedResponse


@dataclass
class ApiResponseFor200Async(api_client.AsyncApiResponse):
    body: CommentsGetAllThreadedResponse


_response_for_200 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor200,
    response_cls_async=ApiResponseFor200Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationJson),
    },
)
SchemaFor404ResponseBodyApplicationJson = CommentsGetAllThreaded404ResponseSchema


@dataclass
class ApiResponseFor404(api_client.ApiResponse):
    body: CommentsGetAllThreaded404Response


@dataclass
class ApiResponseFor404Async(api_client.AsyncApiResponse):
    body: CommentsGetAllThreaded404Response


_response_for_404 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor404,
    response_cls_async=ApiResponseFor404Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor404ResponseBodyApplicationJson),
    },
)
_status_code_to_response = {
    '200': _response_for_200,
    '404': _response_for_404,
}
_all_accept_content_types = (
    'application/json',
)


class BaseApi(api_client.Api):

    def _get_all_threaded_mapped_args(
        self,
        per_page: typing.Optional[int] = None,
        a_id: typing.Optional[str] = None,
        p_id: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
    ) -> api_client.MappedArgs:
        args: api_client.MappedArgs = api_client.MappedArgs()
        _query_params = {}
        if per_page is not None:
            _query_params["per_page"] = per_page
        if a_id is not None:
            _query_params["a_id"] = a_id
        if p_id is not None:
            _query_params["p_id"] = p_id
        if page is not None:
            _query_params["page"] = page
        args.query = _query_params
        return args

    async def _aget_all_threaded_oapg(
        self,
            query_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        """
        Comments
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestQueryParams, query_params)
        used_path = path.value
    
        prefix_separator_iterator = None
        for parameter in (
            request_query_per_page,
            request_query_a_id,
            request_query_p_id,
            request_query_page,
        ):
            parameter_data = query_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            if prefix_separator_iterator is None:
                prefix_separator_iterator = parameter.get_prefix_separator_iterator()
            serialized_data = parameter.serialize(parameter_data, prefix_separator_iterator)
            for serialized_value in serialized_data.values():
                used_path += serialized_value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'get'.upper()
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/api/comments',
            headers=_headers,
        )
    
        response = await self.api_client.async_call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            prefix_separator_iterator=prefix_separator_iterator,
            timeout=timeout,
            **kwargs
        )
    
        if stream:
            if not 200 <= response.http_response.status <= 299:
                body = (await response.http_response.content.read()).decode("utf-8")
                raise exceptions.ApiStreamingException(
                    status=response.http_response.status,
                    reason=response.http_response.reason,
                    body=body,
                )
    
            async def stream_iterator():
                """
                iterates over response.http_response.content and closes connection once iteration has finished
                """
                async for line in response.http_response.content:
                    if line == b'\r\n':
                        continue
                    yield line
                response.http_response.close()
                await response.session.close()
            return AsyncGeneratorResponse(
                content=stream_iterator(),
                headers=response.http_response.headers,
                status=response.http_response.status,
                response=response.http_response
            )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = await response_for_status.deserialize_async(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserializationAsync(
                body=await response.http_response.json() if is_json else await response.http_response.text(),
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        # cleanup session / response
        response.http_response.close()
        await response.session.close()
    
        return api_response


    def _get_all_threaded_oapg(
        self,
            query_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        """
        Comments
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestQueryParams, query_params)
        used_path = path.value
    
        prefix_separator_iterator = None
        for parameter in (
            request_query_per_page,
            request_query_a_id,
            request_query_p_id,
            request_query_page,
        ):
            parameter_data = query_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            if prefix_separator_iterator is None:
                prefix_separator_iterator = parameter.get_prefix_separator_iterator()
            serialized_data = parameter.serialize(parameter_data, prefix_separator_iterator)
            for serialized_value in serialized_data.values():
                used_path += serialized_value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'get'.upper()
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/api/comments',
            headers=_headers,
        )
    
        response = self.api_client.call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            prefix_separator_iterator=prefix_separator_iterator,
            timeout=timeout,
        )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = response_for_status.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserialization(
                body=json.loads(response.http_response.data) if is_json else response.http_response.data,
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        return api_response


class GetAllThreadedRaw(BaseApi):
    # this class is used by api classes that refer to endpoints with operationId fn names

    async def aget_all_threaded(
        self,
        per_page: typing.Optional[int] = None,
        a_id: typing.Optional[str] = None,
        p_id: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._get_all_threaded_mapped_args(
            per_page=per_page,
            a_id=a_id,
            p_id=p_id,
            page=page,
        )
        return await self._aget_all_threaded_oapg(
            query_params=args.query,
            **kwargs,
        )
    
    def get_all_threaded(
        self,
        per_page: typing.Optional[int] = None,
        a_id: typing.Optional[str] = None,
        p_id: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._get_all_threaded_mapped_args(
            per_page=per_page,
            a_id=a_id,
            p_id=p_id,
            page=page,
        )
        return self._get_all_threaded_oapg(
            query_params=args.query,
        )

class GetAllThreaded(BaseApi):

    async def aget_all_threaded(
        self,
        per_page: typing.Optional[int] = None,
        a_id: typing.Optional[str] = None,
        p_id: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        validate: bool = False,
        **kwargs,
    ) -> CommentsGetAllThreadedResponsePydantic:
        raw_response = await self.raw.aget_all_threaded(
            per_page=per_page,
            a_id=a_id,
            p_id=p_id,
            page=page,
            **kwargs,
        )
        if validate:
            return RootModel[CommentsGetAllThreadedResponsePydantic](raw_response.body).root
        return api_client.construct_model_instance(CommentsGetAllThreadedResponsePydantic, raw_response.body)
    
    
    def get_all_threaded(
        self,
        per_page: typing.Optional[int] = None,
        a_id: typing.Optional[str] = None,
        p_id: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        validate: bool = False,
    ) -> CommentsGetAllThreadedResponsePydantic:
        raw_response = self.raw.get_all_threaded(
            per_page=per_page,
            a_id=a_id,
            p_id=p_id,
            page=page,
        )
        if validate:
            return RootModel[CommentsGetAllThreadedResponsePydantic](raw_response.body).root
        return api_client.construct_model_instance(CommentsGetAllThreadedResponsePydantic, raw_response.body)


class ApiForget(BaseApi):
    # this class is used by api classes that refer to endpoints by path and http method names

    async def aget(
        self,
        per_page: typing.Optional[int] = None,
        a_id: typing.Optional[str] = None,
        p_id: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._get_all_threaded_mapped_args(
            per_page=per_page,
            a_id=a_id,
            p_id=p_id,
            page=page,
        )
        return await self._aget_all_threaded_oapg(
            query_params=args.query,
            **kwargs,
        )
    
    def get(
        self,
        per_page: typing.Optional[int] = None,
        a_id: typing.Optional[str] = None,
        p_id: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._get_all_threaded_mapped_args(
            per_page=per_page,
            a_id=a_id,
            p_id=p_id,
            page=page,
        )
        return self._get_all_threaded_oapg(
            query_params=args.query,
        )

