# coding: utf-8

"""
    Forem API V1

    Access Forem articles, users and other resources via API.         For a real-world example of Forem in action, check out [DEV](https://www.dev.to).         All endpoints can be accessed with the 'api-key' header and a accept header, but         some of them are accessible publicly without authentication.          Dates and date times, unless otherwise specified, must be in         the [RFC 3339](https://tools.ietf.org/html/rfc3339) format.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from dev_python_sdk import schemas  # noqa: F401


class ArticleIndex(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Representation of an article or post returned in a list
    """


    class MetaOapg:
        required = {
            "readable_publish_date",
            "created_at",
            "description",
            "canonical_url",
            "title",
            "url",
            "tags",
            "social_image",
            "path",
            "positive_reactions_count",
            "comments_count",
            "tag_list",
            "last_comment_at",
            "public_reactions_count",
            "edited_at",
            "type_of",
            "cover_image",
            "id",
            "published_at",
            "reading_time_minutes",
            "crossposted_at",
            "published_timestamp",
            "user",
            "slug",
        }
        
        class properties:
            tags = schemas.StrSchema
            title = schemas.StrSchema
            description = schemas.StrSchema
            type_of = schemas.StrSchema
            id = schemas.Int32Schema
            
            
            class cover_image(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                class MetaOapg:
                    format = 'url'
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'cover_image':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            readable_publish_date = schemas.StrSchema
            social_image = schemas.StrSchema
        
            @staticmethod
            def tag_list() -> typing.Type['ArticleIndexTagList']:
                return ArticleIndexTagList
            slug = schemas.StrSchema
            path = schemas.StrSchema
            url = schemas.StrSchema
            canonical_url = schemas.StrSchema
            positive_reactions_count = schemas.Int32Schema
            public_reactions_count = schemas.Int32Schema
            created_at = schemas.DateTimeSchema
            
            
            class edited_at(
                schemas.DateTimeBase,
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                class MetaOapg:
                    format = 'date-time'
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, datetime, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'edited_at':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class crossposted_at(
                schemas.DateTimeBase,
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                class MetaOapg:
                    format = 'date-time'
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, datetime, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'crossposted_at':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            published_at = schemas.DateTimeSchema
            last_comment_at = schemas.DateTimeSchema
            published_timestamp = schemas.DateTimeSchema
            reading_time_minutes = schemas.Int32Schema
        
            @staticmethod
            def user() -> typing.Type['SharedUser']:
                return SharedUser
        
            @staticmethod
            def flare_tag() -> typing.Type['ArticleFlareTag']:
                return ArticleFlareTag
        
            @staticmethod
            def organization() -> typing.Type['SharedOrganization']:
                return SharedOrganization
            __annotations__ = {
                "tags": tags,
                "title": title,
                "description": description,
                "type_of": type_of,
                "id": id,
                "cover_image": cover_image,
                "readable_publish_date": readable_publish_date,
                "social_image": social_image,
                "tag_list": tag_list,
                "slug": slug,
                "path": path,
                "url": url,
                "canonical_url": canonical_url,
                "positive_reactions_count": positive_reactions_count,
                "public_reactions_count": public_reactions_count,
                "created_at": created_at,
                "edited_at": edited_at,
                "crossposted_at": crossposted_at,
                "published_at": published_at,
                "last_comment_at": last_comment_at,
                "published_timestamp": published_timestamp,
                "reading_time_minutes": reading_time_minutes,
                "user": user,
                "flare_tag": flare_tag,
                "organization": organization,
            }
    
    readable_publish_date: MetaOapg.properties.readable_publish_date
    created_at: MetaOapg.properties.created_at
    description: MetaOapg.properties.description
    canonical_url: MetaOapg.properties.canonical_url
    title: MetaOapg.properties.title
    url: MetaOapg.properties.url
    tags: MetaOapg.properties.tags
    social_image: MetaOapg.properties.social_image
    path: MetaOapg.properties.path
    positive_reactions_count: MetaOapg.properties.positive_reactions_count
    comments_count: schemas.AnyTypeSchema
    tag_list: 'ArticleIndexTagList'
    last_comment_at: MetaOapg.properties.last_comment_at
    public_reactions_count: MetaOapg.properties.public_reactions_count
    edited_at: MetaOapg.properties.edited_at
    type_of: MetaOapg.properties.type_of
    cover_image: MetaOapg.properties.cover_image
    id: MetaOapg.properties.id
    published_at: MetaOapg.properties.published_at
    reading_time_minutes: MetaOapg.properties.reading_time_minutes
    crossposted_at: MetaOapg.properties.crossposted_at
    published_timestamp: MetaOapg.properties.published_timestamp
    user: 'SharedUser'
    slug: MetaOapg.properties.slug
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["tags"]) -> MetaOapg.properties.tags: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["title"]) -> MetaOapg.properties.title: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["description"]) -> MetaOapg.properties.description: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["type_of"]) -> MetaOapg.properties.type_of: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["id"]) -> MetaOapg.properties.id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["cover_image"]) -> MetaOapg.properties.cover_image: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["readable_publish_date"]) -> MetaOapg.properties.readable_publish_date: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["social_image"]) -> MetaOapg.properties.social_image: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["tag_list"]) -> 'ArticleIndexTagList': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["slug"]) -> MetaOapg.properties.slug: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["path"]) -> MetaOapg.properties.path: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["url"]) -> MetaOapg.properties.url: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["canonical_url"]) -> MetaOapg.properties.canonical_url: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["positive_reactions_count"]) -> MetaOapg.properties.positive_reactions_count: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["public_reactions_count"]) -> MetaOapg.properties.public_reactions_count: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["created_at"]) -> MetaOapg.properties.created_at: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["edited_at"]) -> MetaOapg.properties.edited_at: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["crossposted_at"]) -> MetaOapg.properties.crossposted_at: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["published_at"]) -> MetaOapg.properties.published_at: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["last_comment_at"]) -> MetaOapg.properties.last_comment_at: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["published_timestamp"]) -> MetaOapg.properties.published_timestamp: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["reading_time_minutes"]) -> MetaOapg.properties.reading_time_minutes: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["user"]) -> 'SharedUser': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["flare_tag"]) -> 'ArticleFlareTag': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["organization"]) -> 'SharedOrganization': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["tags", "title", "description", "type_of", "id", "cover_image", "readable_publish_date", "social_image", "tag_list", "slug", "path", "url", "canonical_url", "positive_reactions_count", "public_reactions_count", "created_at", "edited_at", "crossposted_at", "published_at", "last_comment_at", "published_timestamp", "reading_time_minutes", "user", "flare_tag", "organization", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["tags"]) -> MetaOapg.properties.tags: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["title"]) -> MetaOapg.properties.title: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["description"]) -> MetaOapg.properties.description: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["type_of"]) -> MetaOapg.properties.type_of: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["id"]) -> MetaOapg.properties.id: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["cover_image"]) -> MetaOapg.properties.cover_image: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["readable_publish_date"]) -> MetaOapg.properties.readable_publish_date: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["social_image"]) -> MetaOapg.properties.social_image: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["tag_list"]) -> 'ArticleIndexTagList': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["slug"]) -> MetaOapg.properties.slug: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["path"]) -> MetaOapg.properties.path: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["url"]) -> MetaOapg.properties.url: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["canonical_url"]) -> MetaOapg.properties.canonical_url: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["positive_reactions_count"]) -> MetaOapg.properties.positive_reactions_count: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["public_reactions_count"]) -> MetaOapg.properties.public_reactions_count: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["created_at"]) -> MetaOapg.properties.created_at: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["edited_at"]) -> MetaOapg.properties.edited_at: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["crossposted_at"]) -> MetaOapg.properties.crossposted_at: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["published_at"]) -> MetaOapg.properties.published_at: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["last_comment_at"]) -> MetaOapg.properties.last_comment_at: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["published_timestamp"]) -> MetaOapg.properties.published_timestamp: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["reading_time_minutes"]) -> MetaOapg.properties.reading_time_minutes: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["user"]) -> 'SharedUser': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["flare_tag"]) -> typing.Union['ArticleFlareTag', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["organization"]) -> typing.Union['SharedOrganization', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["tags", "title", "description", "type_of", "id", "cover_image", "readable_publish_date", "social_image", "tag_list", "slug", "path", "url", "canonical_url", "positive_reactions_count", "public_reactions_count", "created_at", "edited_at", "crossposted_at", "published_at", "last_comment_at", "published_timestamp", "reading_time_minutes", "user", "flare_tag", "organization", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        readable_publish_date: typing.Union[MetaOapg.properties.readable_publish_date, str, ],
        created_at: typing.Union[MetaOapg.properties.created_at, str, datetime, ],
        description: typing.Union[MetaOapg.properties.description, str, ],
        canonical_url: typing.Union[MetaOapg.properties.canonical_url, str, ],
        title: typing.Union[MetaOapg.properties.title, str, ],
        url: typing.Union[MetaOapg.properties.url, str, ],
        tags: typing.Union[MetaOapg.properties.tags, str, ],
        social_image: typing.Union[MetaOapg.properties.social_image, str, ],
        path: typing.Union[MetaOapg.properties.path, str, ],
        positive_reactions_count: typing.Union[MetaOapg.properties.positive_reactions_count, decimal.Decimal, int, ],
        comments_count: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
        tag_list: 'ArticleIndexTagList',
        last_comment_at: typing.Union[MetaOapg.properties.last_comment_at, str, datetime, ],
        public_reactions_count: typing.Union[MetaOapg.properties.public_reactions_count, decimal.Decimal, int, ],
        edited_at: typing.Union[MetaOapg.properties.edited_at, None, str, datetime, ],
        type_of: typing.Union[MetaOapg.properties.type_of, str, ],
        cover_image: typing.Union[MetaOapg.properties.cover_image, None, str, ],
        id: typing.Union[MetaOapg.properties.id, decimal.Decimal, int, ],
        published_at: typing.Union[MetaOapg.properties.published_at, str, datetime, ],
        reading_time_minutes: typing.Union[MetaOapg.properties.reading_time_minutes, decimal.Decimal, int, ],
        crossposted_at: typing.Union[MetaOapg.properties.crossposted_at, None, str, datetime, ],
        published_timestamp: typing.Union[MetaOapg.properties.published_timestamp, str, datetime, ],
        user: 'SharedUser',
        slug: typing.Union[MetaOapg.properties.slug, str, ],
        flare_tag: typing.Union['ArticleFlareTag', schemas.Unset] = schemas.unset,
        organization: typing.Union['SharedOrganization', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ArticleIndex':
        return super().__new__(
            cls,
            *args,
            readable_publish_date=readable_publish_date,
            created_at=created_at,
            description=description,
            canonical_url=canonical_url,
            title=title,
            url=url,
            tags=tags,
            social_image=social_image,
            path=path,
            positive_reactions_count=positive_reactions_count,
            comments_count=comments_count,
            tag_list=tag_list,
            last_comment_at=last_comment_at,
            public_reactions_count=public_reactions_count,
            edited_at=edited_at,
            type_of=type_of,
            cover_image=cover_image,
            id=id,
            published_at=published_at,
            reading_time_minutes=reading_time_minutes,
            crossposted_at=crossposted_at,
            published_timestamp=published_timestamp,
            user=user,
            slug=slug,
            flare_tag=flare_tag,
            organization=organization,
            _configuration=_configuration,
            **kwargs,
        )

from dev_python_sdk.model.article_flare_tag import ArticleFlareTag
from dev_python_sdk.model.article_index_tag_list import ArticleIndexTagList
from dev_python_sdk.model.shared_organization import SharedOrganization
from dev_python_sdk.model.shared_user import SharedUser
