# coding: utf-8

"""
    Forem API V1

    Access Forem articles, users and other resources via API.         For a real-world example of Forem in action, check out [DEV](https://www.dev.to).         All endpoints can be accessed with the 'api-key' header and a accept header, but         some of them are accessible publicly without authentication.          Dates and date times, unless otherwise specified, must be in         the [RFC 3339](https://tools.ietf.org/html/rfc3339) format.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from dev_python_sdk import schemas  # noqa: F401


class SegmentsAddUsersToSegmentResponse(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
        
            @staticmethod
            def succeeded() -> typing.Type['SegmentsAddUsersToSegmentResponseSucceeded']:
                return SegmentsAddUsersToSegmentResponseSucceeded
        
            @staticmethod
            def failed() -> typing.Type['SegmentsAddUsersToSegmentResponseFailed']:
                return SegmentsAddUsersToSegmentResponseFailed
            __annotations__ = {
                "succeeded": succeeded,
                "failed": failed,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["succeeded"]) -> 'SegmentsAddUsersToSegmentResponseSucceeded': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["failed"]) -> 'SegmentsAddUsersToSegmentResponseFailed': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["succeeded", "failed", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["succeeded"]) -> typing.Union['SegmentsAddUsersToSegmentResponseSucceeded', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["failed"]) -> typing.Union['SegmentsAddUsersToSegmentResponseFailed', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["succeeded", "failed", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        succeeded: typing.Union['SegmentsAddUsersToSegmentResponseSucceeded', schemas.Unset] = schemas.unset,
        failed: typing.Union['SegmentsAddUsersToSegmentResponseFailed', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'SegmentsAddUsersToSegmentResponse':
        return super().__new__(
            cls,
            *args,
            succeeded=succeeded,
            failed=failed,
            _configuration=_configuration,
            **kwargs,
        )

from dev_python_sdk.model.segments_add_users_to_segment_response_failed import SegmentsAddUsersToSegmentResponseFailed
from dev_python_sdk.model.segments_add_users_to_segment_response_succeeded import SegmentsAddUsersToSegmentResponseSucceeded
