# coding: utf-8

"""
    Forem API V1

    Access Forem articles, users and other resources via API.         For a real-world example of Forem in action, check out [DEV](https://www.dev.to).         All endpoints can be accessed with the 'api-key' header and a accept header, but         some of them are accessible publicly without authentication.          Dates and date times, unless otherwise specified, must be in         the [RFC 3339](https://tools.ietf.org/html/rfc3339) format.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from dataclasses import dataclass
import typing_extensions
import urllib3
from pydantic import RootModel
from dev_python_sdk.request_before_hook import request_before_hook
import json
from urllib3._collections import HTTPHeaderDict

from dev_python_sdk.api_response import AsyncGeneratorResponse
from dev_python_sdk import api_client, exceptions
from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from dev_python_sdk import schemas  # noqa: F401

from dev_python_sdk.model.pages_create_new_page401_response import PagesCreateNewPage401Response as PagesCreateNewPage401ResponseSchema
from dev_python_sdk.model.pages_create_new_page422_response import PagesCreateNewPage422Response as PagesCreateNewPage422ResponseSchema
from dev_python_sdk.model.pages_create_new_page_request import PagesCreateNewPageRequest as PagesCreateNewPageRequestSchema
from dev_python_sdk.model.pages_create_new_page_response import PagesCreateNewPageResponse as PagesCreateNewPageResponseSchema

from dev_python_sdk.type.pages_create_new_page_response import PagesCreateNewPageResponse
from dev_python_sdk.type.pages_create_new_page_request import PagesCreateNewPageRequest
from dev_python_sdk.type.pages_create_new_page401_response import PagesCreateNewPage401Response
from dev_python_sdk.type.pages_create_new_page422_response import PagesCreateNewPage422Response

from ...api_client import Dictionary
from dev_python_sdk.pydantic.pages_create_new_page401_response import PagesCreateNewPage401Response as PagesCreateNewPage401ResponsePydantic
from dev_python_sdk.pydantic.pages_create_new_page422_response import PagesCreateNewPage422Response as PagesCreateNewPage422ResponsePydantic
from dev_python_sdk.pydantic.pages_create_new_page_response import PagesCreateNewPageResponse as PagesCreateNewPageResponsePydantic
from dev_python_sdk.pydantic.pages_create_new_page_request import PagesCreateNewPageRequest as PagesCreateNewPageRequestPydantic

from . import path

# body param
SchemaForRequestBodyApplicationJson = PagesCreateNewPageRequestSchema


request_body_pages_create_new_page_request = api_client.RequestBody(
    content={
        'application/json': api_client.MediaType(
            schema=SchemaForRequestBodyApplicationJson),
    },
)
_auth = [
    'api-key',
]
SchemaFor200ResponseBodyApplicationJson = PagesCreateNewPageResponseSchema


@dataclass
class ApiResponseFor200(api_client.ApiResponse):
    body: PagesCreateNewPageResponse


@dataclass
class ApiResponseFor200Async(api_client.AsyncApiResponse):
    body: PagesCreateNewPageResponse


_response_for_200 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor200,
    response_cls_async=ApiResponseFor200Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationJson),
    },
)
SchemaFor401ResponseBodyApplicationJson = PagesCreateNewPage401ResponseSchema


@dataclass
class ApiResponseFor401(api_client.ApiResponse):
    body: PagesCreateNewPage401Response


@dataclass
class ApiResponseFor401Async(api_client.AsyncApiResponse):
    body: PagesCreateNewPage401Response


_response_for_401 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor401,
    response_cls_async=ApiResponseFor401Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor401ResponseBodyApplicationJson),
    },
)
SchemaFor422ResponseBodyApplicationJson = PagesCreateNewPage422ResponseSchema


@dataclass
class ApiResponseFor422(api_client.ApiResponse):
    body: PagesCreateNewPage422Response


@dataclass
class ApiResponseFor422Async(api_client.AsyncApiResponse):
    body: PagesCreateNewPage422Response


_response_for_422 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor422,
    response_cls_async=ApiResponseFor422Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor422ResponseBodyApplicationJson),
    },
)
_status_code_to_response = {
    '200': _response_for_200,
    '401': _response_for_401,
    '422': _response_for_422,
}
_all_accept_content_types = (
    'application/json',
)


class BaseApi(api_client.Api):

    def _create_new_page_mapped_args(
        self,
        title: typing.Optional[str] = None,
        description: typing.Optional[str] = None,
        slug: typing.Optional[str] = None,
        body_markdown: typing.Optional[str] = None,
        body_json: typing.Optional[str] = None,
        is_top_level_path: typing.Optional[bool] = None,
        template: typing.Optional[str] = None,
    ) -> api_client.MappedArgs:
        args: api_client.MappedArgs = api_client.MappedArgs()
        _body = {}
        if title is not None:
            _body["title"] = title
        if description is not None:
            _body["description"] = description
        if slug is not None:
            _body["slug"] = slug
        if body_markdown is not None:
            _body["body_markdown"] = body_markdown
        if body_json is not None:
            _body["body_json"] = body_json
        if is_top_level_path is not None:
            _body["is_top_level_path"] = is_top_level_path
        if template is not None:
            _body["template"] = template
        args.body = _body
        return args

    async def _acreate_new_page_oapg(
        self,
        body: typing.Any = None,
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        content_type: str = 'application/json',
        stream: bool = False,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        """
        pages
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        used_path = path.value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'post'.upper()
        _headers.add('Content-Type', content_type)
    
        _fields = None
        _body = None
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/api/pages',
            body=body,
            auth_settings=_auth,
            headers=_headers,
        )
        if body is not schemas.unset:
            serialized_data = request_body_pages_create_new_page_request.serialize(body, content_type)
            if 'fields' in serialized_data:
                _fields = serialized_data['fields']
            elif 'body' in serialized_data:
                _body = serialized_data['body']
    
        response = await self.api_client.async_call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            fields=_fields,
            serialized_body=_body,
            body=body,
            auth_settings=_auth,
            timeout=timeout,
            **kwargs
        )
    
        if stream:
            if not 200 <= response.http_response.status <= 299:
                body = (await response.http_response.content.read()).decode("utf-8")
                raise exceptions.ApiStreamingException(
                    status=response.http_response.status,
                    reason=response.http_response.reason,
                    body=body,
                )
    
            async def stream_iterator():
                """
                iterates over response.http_response.content and closes connection once iteration has finished
                """
                async for line in response.http_response.content:
                    if line == b'\r\n':
                        continue
                    yield line
                response.http_response.close()
                await response.session.close()
            return AsyncGeneratorResponse(
                content=stream_iterator(),
                headers=response.http_response.headers,
                status=response.http_response.status,
                response=response.http_response
            )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = await response_for_status.deserialize_async(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserializationAsync(
                body=await response.http_response.json() if is_json else await response.http_response.text(),
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        # cleanup session / response
        response.http_response.close()
        await response.session.close()
    
        return api_response


    def _create_new_page_oapg(
        self,
        body: typing.Any = None,
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        content_type: str = 'application/json',
        stream: bool = False,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        """
        pages
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        used_path = path.value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'post'.upper()
        _headers.add('Content-Type', content_type)
    
        _fields = None
        _body = None
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/api/pages',
            body=body,
            auth_settings=_auth,
            headers=_headers,
        )
        if body is not schemas.unset:
            serialized_data = request_body_pages_create_new_page_request.serialize(body, content_type)
            if 'fields' in serialized_data:
                _fields = serialized_data['fields']
            elif 'body' in serialized_data:
                _body = serialized_data['body']
    
        response = self.api_client.call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            fields=_fields,
            serialized_body=_body,
            body=body,
            auth_settings=_auth,
            timeout=timeout,
        )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = response_for_status.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserialization(
                body=json.loads(response.http_response.data) if is_json else response.http_response.data,
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        return api_response


class CreateNewPageRaw(BaseApi):
    # this class is used by api classes that refer to endpoints with operationId fn names

    async def acreate_new_page(
        self,
        title: typing.Optional[str] = None,
        description: typing.Optional[str] = None,
        slug: typing.Optional[str] = None,
        body_markdown: typing.Optional[str] = None,
        body_json: typing.Optional[str] = None,
        is_top_level_path: typing.Optional[bool] = None,
        template: typing.Optional[str] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._create_new_page_mapped_args(
            title=title,
            description=description,
            slug=slug,
            body_markdown=body_markdown,
            body_json=body_json,
            is_top_level_path=is_top_level_path,
            template=template,
        )
        return await self._acreate_new_page_oapg(
            body=args.body,
            **kwargs,
        )
    
    def create_new_page(
        self,
        title: typing.Optional[str] = None,
        description: typing.Optional[str] = None,
        slug: typing.Optional[str] = None,
        body_markdown: typing.Optional[str] = None,
        body_json: typing.Optional[str] = None,
        is_top_level_path: typing.Optional[bool] = None,
        template: typing.Optional[str] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._create_new_page_mapped_args(
            title=title,
            description=description,
            slug=slug,
            body_markdown=body_markdown,
            body_json=body_json,
            is_top_level_path=is_top_level_path,
            template=template,
        )
        return self._create_new_page_oapg(
            body=args.body,
        )

class CreateNewPage(BaseApi):

    async def acreate_new_page(
        self,
        title: typing.Optional[str] = None,
        description: typing.Optional[str] = None,
        slug: typing.Optional[str] = None,
        body_markdown: typing.Optional[str] = None,
        body_json: typing.Optional[str] = None,
        is_top_level_path: typing.Optional[bool] = None,
        template: typing.Optional[str] = None,
        validate: bool = False,
        **kwargs,
    ) -> PagesCreateNewPageResponsePydantic:
        raw_response = await self.raw.acreate_new_page(
            title=title,
            description=description,
            slug=slug,
            body_markdown=body_markdown,
            body_json=body_json,
            is_top_level_path=is_top_level_path,
            template=template,
            **kwargs,
        )
        if validate:
            return PagesCreateNewPageResponsePydantic(**raw_response.body)
        return api_client.construct_model_instance(PagesCreateNewPageResponsePydantic, raw_response.body)
    
    
    def create_new_page(
        self,
        title: typing.Optional[str] = None,
        description: typing.Optional[str] = None,
        slug: typing.Optional[str] = None,
        body_markdown: typing.Optional[str] = None,
        body_json: typing.Optional[str] = None,
        is_top_level_path: typing.Optional[bool] = None,
        template: typing.Optional[str] = None,
        validate: bool = False,
    ) -> PagesCreateNewPageResponsePydantic:
        raw_response = self.raw.create_new_page(
            title=title,
            description=description,
            slug=slug,
            body_markdown=body_markdown,
            body_json=body_json,
            is_top_level_path=is_top_level_path,
            template=template,
        )
        if validate:
            return PagesCreateNewPageResponsePydantic(**raw_response.body)
        return api_client.construct_model_instance(PagesCreateNewPageResponsePydantic, raw_response.body)


class ApiForpost(BaseApi):
    # this class is used by api classes that refer to endpoints by path and http method names

    async def apost(
        self,
        title: typing.Optional[str] = None,
        description: typing.Optional[str] = None,
        slug: typing.Optional[str] = None,
        body_markdown: typing.Optional[str] = None,
        body_json: typing.Optional[str] = None,
        is_top_level_path: typing.Optional[bool] = None,
        template: typing.Optional[str] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._create_new_page_mapped_args(
            title=title,
            description=description,
            slug=slug,
            body_markdown=body_markdown,
            body_json=body_json,
            is_top_level_path=is_top_level_path,
            template=template,
        )
        return await self._acreate_new_page_oapg(
            body=args.body,
            **kwargs,
        )
    
    def post(
        self,
        title: typing.Optional[str] = None,
        description: typing.Optional[str] = None,
        slug: typing.Optional[str] = None,
        body_markdown: typing.Optional[str] = None,
        body_json: typing.Optional[str] = None,
        is_top_level_path: typing.Optional[bool] = None,
        template: typing.Optional[str] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._create_new_page_mapped_args(
            title=title,
            description=description,
            slug=slug,
            body_markdown=body_markdown,
            body_json=body_json,
            is_top_level_path=is_top_level_path,
            template=template,
        )
        return self._create_new_page_oapg(
            body=args.body,
        )

